print("Hey hey!")
name = input("What is your name? ")
food = input("What is your favorite food? ")
music = input("And what is your favorite music genre? ")
location = input("Where do you come from? ")

print("Short summary about you:")
print("Your name is ")
print(name)
print("And you enjoy eating ")
print(food)
print("And you enjoy listening to ")
print(music)
print("As originally you are from")
print(location)
print("Have a nice day!")
